export CUDA_VISIBLE_DEVICES=1

python -u run.py \
  --is_training 1 \
  --root_path ./data/ \
  --data_path air_quality.csv \
  --model_id air_quality_96_96 \
  --model Autoformer \
  --data custom \
  --features M \
  --target CO(GT) \
  --freq h \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 96 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 8 \
  --dec_in 8 \
  --c_out 8 \
  --des 'AirQuality' \
  --itr 1 \
  --train_epochs 2

python -u run.py \
  --is_training 1 \
  --root_path ./data/ \
  --data_path air_quality.csv \
  --model_id air_quality_96_192 \
  --model Autoformer \
  --data custom \
  --features M \
  --target CO(GT) \
  --freq h \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 192 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 8 \
  --dec_in 8 \
  --c_out 8 \
  --des 'AirQuality' \
  --itr 1 \
  --train_epochs 2

python -u run.py \
  --is_training 1 \
  --root_path ./data/ \
  --data_path air_quality.csv \
  --model_id air_quality_96_336 \
  --model Autoformer \
  --data custom \
  --features M \
  --target CO(GT) \
  --freq h \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 336 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 8 \
  --dec_in 8 \
  --c_out 8 \
  --des 'AirQuality' \
  --itr 1 \
  --train_epochs 2

python -u run.py \
  --is_training 1 \
  --root_path ./data/ \
  --data_path air_quality.csv \
  --model_id air_quality_96_720 \
  --model Autoformer \
  --data custom \
  --features M \
  --target CO(GT) \
  --freq h \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 720 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 8 \
  --dec_in 8 \
  --c_out 8 \
  --des 'AirQuality' \
  --itr 1 \
  --train_epochs 2